// <auto-generated />
using System;
using BookingHistoryService.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingHistoryService.DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingHistoryService.DataAccessLayer.Entities.BookingHistory", b =>
                {
                    b.Property<string>("BookingId")
                        .HasColumnType("text")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HotelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hotel_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId")
                        .HasName("pk_booking_history");

                    b.ToTable("booking_history", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
