replicaCount: 1

image:
  name: booking-service
  tag: latest
  pullPolicy: Never        # локальный образ в minikube

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ENABLE_FEATURE_X: true     # фича включена в staging

env: [] # TODO
#  - name: APP_ENV
#    value: prod
#  - name: LOG_LEVEL
#    value: info

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

livenessProbe:
  path: /ping
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  path: /ping
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1